@echo off
REM ****************************************************************************
REM Vivado (TM) v2025.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Mon Nov 03 01:43:44 +0200 2025
REM SW Build 6140274 on Thu May 22 00:12:29 MDT 2025
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim tb_SRC_behav -key {Behavioral:sim_1:Functional:tb_SRC} -tclbatch tb_SRC.tcl -view C:/Users/matan/OneDrive/Desktop/simple_riscV/tb_control_unit_behav1.wcfg -view C:/Users/matan/OneDrive/Desktop/simple_riscV/SRC_top_behav.wcfg -log simulate.log"
call xsim  tb_SRC_behav -key {Behavioral:sim_1:Functional:tb_SRC} -tclbatch tb_SRC.tcl -view C:/Users/matan/OneDrive/Desktop/simple_riscV/tb_control_unit_behav1.wcfg -view C:/Users/matan/OneDrive/Desktop/simple_riscV/SRC_top_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
